# Generated by Django 4.2.7 on 2025-07-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0002_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="company",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="education",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_public_profile",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="receive_email_notifications",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="receive_sms_notifications",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="state",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="twitter",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="website",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="About"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Age"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Full Name"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_profiles/",
                verbose_name="Profile Image",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Last Name"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone Number"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("customer", "Customer"),
                    ("vendor", "Vendor"),
                    ("admin", "Admin"),
                ],
                max_length=10,
                null=True,
                verbose_name="User Type",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Country"
            ),
        ),
    ]
